version: '3.1'
services:
  mariadb:
    container_name: mariadb
    build: requirements/mariadb
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - docker_network
    ports:
      - "3306:3306"
    restart: always
  wordpress:
    build: requirements/wordpress
    container_name: wordpress
    depends_on: 
      - mariadb
    networks:
      - docker_network
    ports:
      - "9000:9000"
    volumes:
      - wordpress_data:/var/www/html/wordpress
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_HOST: ${MYSQL_HOST}
  nginx:
    container_name: nginx
    build: requirements/nginx
    depends_on :
      - wordpress
    networks:
      - docker_network
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html/wordpress
    restart: always

networks:
  docker_network:

volumes:
  db_data: 
    driver: local
    driver_opts:
      type: none
      device: /home/llescure/data/mysql
      o: bind
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /home/llescure/data/wordpress
      o: bind

