version: '3'
services:
  mariadb:
    container_name: mariadb
    build:
      context: requirements/mariadb
      dockerfile: requirements/mariadb/Dockerfile
      image: mariadb:v1
      volumes:
          - mysql:/var/lib/mysql
      environment:
        MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        MYSQL_DATABASE=${MYSQL_DATABASE}
        MYSQL_USER=${MYSQL_USER}
        MYSQL_PASSWORD=${MYSQL_PASSWORD}
      network:
          docker_network
      ports: "3306:3306"
      restart: always
services:
    nginx:
        container_name: nginx
        build:
          context: requirements/nginx
          dockerfile: requirements/nginx/Dockerfile
          image: nginx:v1
      network:
          docker_network
      ports: "443:443"
      volumes:
          - wordpress:/var/www/html
      restart: always
services:
    wordpress:
      container_name: wordpress
      build:
        context: requirements/wordpress
        dockerfile: requirements/wordpress/Dockerfile
        image: wordpress:v1
      depends on:
        - mariadb
        - nginx
      network:
          docker_network
      ports: "9000:9000"
      volumes:
          - wordpress:/var/www/html
      restart: always
      environment:
        WORDPRESS_DB_HOST={WORDPRESS_DB_HOST}
        WORDPRESS_DB_USER={WORDPRESS_DB_USER}
        WORDPRESS_DB_PASSWORD={WORDPRESS_DB_PASSWORD}
        WORDPRESS_DB_NAME={WORDPRESS_DB_NAME}

volumes:
    wordpress:
        driver: local
        driver opts:
            o: bind
            type: none
            device: /home/llescure/data/wordpress
    mariadb:
        driver: local
        driver opts:
            o: bind
            type: none
            device: /home/llescure/data/mariadb
